# FROM ubuntu-latest
FROM ubuntu:20.04

# Set system env
ENV DEBIAN_FRONTEND=noninteractive

# Install packages
RUN apt-get update \
  && apt-get install -y \
  ssh \
  lsb-release \
  gawk \
  curl \
  git \
  wget \
  sudo \
  gnupg-agent \
  ca-certificates \
  software-properties-common \
  apt-transport-https \
  libyaml-0-2 \
  zstd \
  zip \
  unzip \
  xz-utils \
  psmisc \
  libgtk2.0-0 \
  libgtk-3-0 \
  libgbm-dev \
  libnotify-dev \
  libgconf-2-4 \
  libnss3 \
  libxss1 \
  libasound2 \
  libxtst6 \
  xauth \
  xvfb \
  nodejs \
  npm \
  jq
