version: '3.5'

services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    logging:
      driver: none
    networks:
      - app-network-dev

  app-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: dev
    image: app/server:dev
    ports:
      - 4000:4000
    volumes:
      - ./server:/app/
      - /app/node_modules/
    depends_on:
      - app-db
    environment:
      DB_HOST: app-db
      DB_PORT: ${DB_PORT:-27017}
      DB_USER: ${DB_USER:-app}
      DB_PASSWD: ${DB_PASSWD:-app}
      DB_NAME: ${DB_NAME:-app}
      SMTP_HOST: mailhog
      SMTP_PORT: ${SMTP_PORT:-1025}
      EMAIL_SENDER: ${EMAIL_SENDER:-app@mainbot.me}
      PUBLIC_URL: ${PUBLIC_URL:-http://localhost:8080}
      TOKEN_SECRET: ${TOKEN_SECRET:-secret}
      EXPERIMENTATION: ${EPERIMENTATION:-false}
    restart: on-failure
    command: npm run dev
    networks:
      - app-network-dev

  app-client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: dev
    image: app/client:dev
    ports:
      - 8080:8080
    volumes:
      - ./client:/app/
      - /app/node_modules/
    environment:
      SERVER_HOST: app-server
      SERVER_PORT: 4000
      VITE_APP_EXPERIMENTATION: ${VITE_APP_EXPERIMENTATION:-false}
      VITE_APP_GIT_TAG: ${VITE_APP_GIT_TAG:-local}
      VITE_APP_GIT_SHA: ${VITE_APP_GIT_SHA:-local}
    restart: on-failure
    command: npm start
    networks:
      - app-network-dev

  app-db:
    image: mongo:4.0.16
    ports:
      - 27017:27017
    volumes:
      - ./mongo-dev/db:/data/db
      - ./server/init-db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS:-changeme75}
      MONGO_INITDB_DATABASE: ${DB_NAME:-app}
      DB_USER: ${DB_USER:-app}
      DB_PASSWD: ${DB_PASSWD:-app}
      DB_NAME: ${DB_NAME:-app}
    networks:
      - app-network-dev

  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
      - app-db
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASS:-changeme75}
      ME_CONFIG_MONGODB_SERVER: app-db
    networks:
      - app-network-dev

networks:
  app-network-dev:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
