version: '3.5'

services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    logging:
      driver: none

  app-db:
    image: mongo:4.0.16
    ports:
      - 27017:27017
    volumes:
      - ../mongo-dev/db:/data/db
      - ./init-db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS:-changeme75}
      MONGO_INITDB_DATABASE: ${DB_NAME:-app}
      DB_USER: ${DB_USER:-app}
      DB_PASSWD: ${DB_PASSWD:-app}
      DB_NAME: ${DB_NAME:-app}
    networks:
      - app-network

  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
      - app-db
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASS:-changeme75}
      ME_CONFIG_MONGODB_SERVER: app-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
